server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: XXXX
    username: XXXX
    password: XXXX
    driver-class-name: com.mysql.cj.jdbc.Driver
  #cos密钥
  tengxun:
    SecretId: XXXX
    SecretKey: XXXX
    region: ap-guangzhou
    url: XXXX
    bucketName: XXXX
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: XXXX
  mapper-locations: classpath:com/kivze/mapper/*.xml
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增
  configuration:
    map-underscore-to-camel-case: false # 开启驼峰功能
    auto-mapping-behavior: full # 自动映射任何复杂的结果
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.kivze.util


#对象地址前缀
MyAddress: XXXX

